"""Render a signed-NVFLARE provisioning source from a physical topology.

The command creates *only* non-secret source material.  Certificates and
startup kits are generated by NVIDIA FLARE after an operator explicitly adds
``--provision``.  Do not distribute the resulting private keys through git,
email, or this script.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from rarelink.deployment.topology import (  # noqa: E402
    load_physical_topology,
    render_nvflare_project,
    topology_sha256,
)


def write_rendered_contract(topology_path: Path, output_dir: Path) -> dict[str, object]:
    topology = load_physical_topology(topology_path)
    output_dir.mkdir(parents=True, exist_ok=True)
    project = render_nvflare_project(topology)
    (output_dir / "project.yml").write_text(
        yaml.safe_dump(project, sort_keys=False, allow_unicode=True), encoding="utf-8"
    )
    contract = topology.public_contract()
    receipt = {
        "schema_version": "rarelink-physical-provision-source-v1",
        "rendered_at_utc": datetime.now(UTC).isoformat(),
        "topology_sha256": topology_sha256(topology),
        "federation": contract,
        "contains_patient_data": False,
        "contains_certificates": False,
        "contains_private_keys": False,
        "next_step": "Run nvflare provision only from the coordinator's secured operator host.",
    }
    (output_dir / "deployment-receipt.json").write_text(
        json.dumps(receipt, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    plan = "\n".join(
        [
            "# RareLink physical federation distribution plan",
            "",
            "This directory is deployment source, not a startup kit. Run `nvflare provision` "
            "from the coordinator's approved operator environment, then transfer each generated, "
            "signed kit only",
            "to its named organization through the approved secure delivery process.",
            "",
            f"- Coordinator: `{topology.coordinator.endpoint.hostname}`",
            f"- Client kits: {', '.join(site.site_id for site in topology.sites)}",
            "- Each hospital supplies its own local manifest at the agreed local mount path.",
            "- Never copy images, labels, dataset manifests, `client.key`, `server.key`, or admin "
            "  kits here.",
            "- Do not edit `startup/fed_client.json` or `startup/fed_server.json` after "
            "  provisioning;",
            "  the NVFLARE signature will be invalid. Change topology and regenerate instead.",
            "",
        ]
    )
    (output_dir / "DISTRIBUTION_PLAN.md").write_text(plan, encoding="utf-8")
    return receipt


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Render/provision a physical RareLink FLARE topology"
    )
    parser.add_argument("--topology", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, default=Path("deploy/physical/rendered"))
    parser.add_argument(
        "--provision",
        action="store_true",
        help="Explicitly invoke NVIDIA FLARE provisioning after rendering source files.",
    )
    parser.add_argument(
        "--workspace",
        type=Path,
        default=Path("deploy/physical/provisioned"),
        help="Secure coordinator-only workspace for generated startup kits (git ignored).",
    )
    args = parser.parse_args()

    receipt = write_rendered_contract(args.topology, args.output_dir)
    if args.provision:
        executable = shutil.which("nvflare")
        if not executable:
            raise RuntimeError("NVIDIA FLARE CLI is not installed; install `rarelink[spark]` first")
        subprocess.run(
            [
                executable,
                "provision",
                "-p",
                str((args.output_dir / "project.yml").resolve()),
                "-w",
                str(args.workspace.resolve()),
                "-s",
            ],
            check=True,
        )
        print(
            json.dumps(
                {
                    "provisioning_started": True,
                    "workspace": str(args.workspace.resolve()),
                    "warning": (
                        "Startup kits contain private keys. Keep the workspace coordinator-only."
                    ),
                },
                ensure_ascii=False,
            )
        )
    else:
        print(json.dumps(receipt, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
